### ISSUE TITLE
Shibboleth not loading in 2.4.3 beta2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxIdp#3]
* Shibboleth is not loading. `https://<hostname>/idp/shibboleth` is throwing blank page. This issue has similarity with [another](https://github.com/GluuFederation/oxIdp/issues/2) one @iromli reported. 

* Problem: 

 - `https://<hostname>/idp/shibboleth` is blank
 - No logs inside /opt/idp/logs/

* Stack trace from localhost: http://pastebin.com/kGgdcFbY

* Shibboleth is working in 2.4.2, I just saw two differences so far between 2.4.2 and 2.4.3 beta 2:

- There is no 'identity.xml' inside '/opt/tomcat/conf/Catalina/localhost/' of 2.4.2
- Now all 'ou=configurations' ( oxauth, oxtrust,oxidp, oxcas and oxasimba ) are inside 'ox-ldap.properties' file

**Comment by aliaksander-samuseu** [comment]
Same is for my deb package of beta2.
Here are possibly relevant log fragments from `/opt/tomcat/logs/catalinaXXXX.log`- [link](https://github.com/GluuFederation/oxIdp/files/215774/catalina.txt) - and `/opt/tomcat/logs/localhostXXXX.log` - [link](https://github.com/GluuFederation/oxIdp/files/215780/hostname.txt)

**Comment by mzico** [comment]
@yurem assigned this to you but please feel free to let us know if you need any assistance.

**Comment by yurem** [comment]
1) Starting from 2.4.3 IDP not used $TOMCA_HOME/endorsed folder anymore - [link](https://wiki.shibboleth.net/confluence/display/SHIB2/IdPConfigurationChanges#IdPConfigurationChanges-Shibboleth2.4.3ConfigurationChanges)

2) IDP 2.4.5 not works fine on latest tomcat 7.0.68. But it works fine on tmcat 7.0.65 !

3) There are few IDP 2..45 configuration changes which we need to put into our templates

**Comment by yurem** [comment]
It should be fixed in beta 3
