### ISSUE TITLE
Add GUI option to disable SAML assertion encryption

### ISSUE THREAD

**Issue by zeroluck** [GluuFederation/oxIdp#4]
Feature request: Add GUI option in SAML trust relationships page to disable SAML assertion encryption for a relying party. Some SP's do not support encrypted SAML assertions (Wrike, Zoom, ArcGIS, maybe Ping Identities?). Having this feature would ease configuration:

```
<rp:DefaultRelyingParty provider="https://www.wrike.com"defaultSigningCredentialRef="IdPCredential">...       <rp:ProfileConfiguration xsi:type="saml:SAML2ECPProfile" includeAttributeStatement="true" assertionLifetime="PT5M" assertionProxyCount="0" signResponses="never" signAssertions="always" encryptAssertions="never" encryptNameIds="never"/>...</rp:DefaultRelyingParty>
```

https://support.zoom.us/hc/en-us/articles/203081547-Turning-Off-Assertion-Encryption-in-Shibboleth
https://ping.force.com/Support/PingOne/X3rd-Party-Identity-Bridge/PingOne-How-to-disable-assertion-encryption-in-ADFS
https://doc.arcgis.com/en/arcgis-online/reference/configure-shibboleth.htm#ESRI_SECTION1_F7C6E43325BB4BEEAB591D01B1A14EF7 step 6

**Comment by willow9886** [comment]
Thanks for the suggestion. We'll review.

**Comment by nynymike** [comment]
This issue needs to be raised on the Gluu Support site first to determine if there is a solution: https://support.gluu.org  Only after its determined that its not possible will we move it to github.

**Comment by zeroluck** [comment]
I've opened a support request on how to manually do this: https://support.gluu.org/integrations/disabling-saml-assertion-encryption-2632

Is that request sufficient or should I open an additional request for the GUI option?

**Comment by willow9886** [comment]
this is fine. Thanks, Thomas.
