### ISSUE TITLE
Add 'emailAddress' as default nameID format

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxIdp#5]
Right now we are shipping 'unspecified' and 'transientID' as default nameID out of the box. Seems like 'emailAddress' is also a famous one among many SPs. We can ship 'emailAddress' along with 'unspecified' and 'transientID' format. 

Just add below one as Principal Connector in 'attribute-resolver.xml.vm' 

```
<resolver:PrincipalConnector xsi:type="pc:Transient" id="saml2Transient" nameIDFormat="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" />

```

**Comment by uboznikov** [comment]
@mzico `<PrincipalConnector>` has been depcrecated in [v3](https://wiki.shibboleth.net/confluence/display/IDP30/AttributeResolverConfiguration#AttributeResolverConfiguration-<PrincipalConnector>); however please test this and let me know the results. Thanks.

**Comment by mzico** [comment]
@uboznikov : Okay. Do we have any CE 3.0.0 deb/rpm download link which has v3 enabled?

**Comment by uboznikov** [comment]
@mzico For deb download the latest CE 3.0.0 from Ubuntu devel repo

**Comment by yurem** [comment]
Closing because we have same issue in oxTrust which is right place for this issue
