### ISSUE TITLE
Wrong(?) login handler is selected when SP explicitly requests "PasswordProtectedTransport" authentication method from IdP

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxIdp#6]
We've had this issue reported already twice:
https://support.gluu.org/integrations/idp-invalid-attribute-description-2613
https://support.gluu.org/integrations/saml-sso-troubleshooting-2836#at11354

Environment:
Gluu CE 2.4.3 package, Shibboleth IdP 2.4.5

Preconditions:
1. Some basic SAML TR (using HTTP-redirect bindings) is configured via oxTrust with SP that is under your control (or you are capable in any other way to ensure that SAML request contains `<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>` instruction)

Steps to reproduce:

1. Initiate login flow to the SP while using any means available (like, configuring the SP, or intercepting and modifying the request etc) to ensure that initial request contains  xml element like this (you can find full request mentioned in one of the tickets [here](https://github.com/GluuFederation/oxIdp/files/328994/saml-request.txt)):
```
<samlp:RequestedAuthnContext Comparison="exact">
<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
```

Result:

User is redirected to a standard Shibboleth's login page, located at `https://host.name/idp/Authn/UserPassword`, which doesn't even work out of the box. The cause of the latter seems to be incomplete configuration. Here how it looks like initially:
```
ShibUserPassAuth {
   edu.vt.middleware.ldap.jaas.LdapLoginModule required
	  host="ldaps://localhost:1636"
      subtreeSearch="true"
      base="o=gluu"
      subtreeSearch="true"
      serviceUser="cn=Directory Manager"
      serviceCredential="SOMEPASSWORD"
      userField="";
};
```
..and here is when after the issue is fixed:
```
ShibUserPassAuth {
   edu.vt.middleware.ldap.jaas.LdapLoginModule required
	  host="ldaps://localhost:1636"
      subtreeSearch="true"
      base="o=gluu"
      subtreeSearch="true"
      serviceUser="cn=Directory Manager"
      serviceCredential="SOMEPASSWORD"
      userFilter="uid={0}"
      userField="";
};
```
I.e. it lacks just that one string `userFilter="uid={0}"`

Expected result:

User is redirected (by means of our custom "RemoteUser" login handler) to the our usual oxAuth login page for authentication, then is redirected back to Shibboleth to spawn a session there.

Basically, there seem to 2 issues/questions:

1) Should the "UserPassword" login handler still even be supported? It doesn't even work out of the box. If it was intentionally left there, we need to fix it, at least.
2) Even if this handler belong there, it doesn't seem right that it's being selected instead of our own and more advanced "RemoteUser" handler when SP explicitly requests for "PasswordProtectedTransport" authentication method (which both handlers seem to support). This also should be fixed.

Here is how both handlers' definitions in `/opt/idp/conf/handler.xml` look like currently:
```
    <ph:LoginHandler xsi:type="ph:RemoteUser">
        <ph:AuthenticationMethod>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</ph:AuthenticationMethod>
        <ph:AuthenticationMethod>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</ph:AuthenticationMethod>
    </ph:LoginHandler>

    <!--  Username/password login handler -->

    <ph:LoginHandler xsi:type="ph:UsernamePassword" 
                  jaasConfigurationLocation="file:///opt/idp/conf/login.config">
        <ph:AuthenticationMethod>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</ph:AuthenticationMethod>
    </ph:LoginHandler>
```

That explains why it works as expected when no specific authentication method is requested - it probably resorts to "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified" in that case, which only supported by "RemoteUser" handler.

**Comment by dmogn** [comment]
Mike Schwartz: We dont' support the saml:AuthnContextClassRef tag

**Comment by nynymike** [comment]
This is not a bug. We don't support the AuthnContextClassRef tag. We never have... if this is to be supported, it would only be in Shib IDP v3.
